
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sklad.Classes
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int ID { get; set; }

    public int IDbasket { get; set; }

    public int IDmedicament { get; set; }

    public int Kolvo { get; set; }



    public virtual Basket Basket { get; set; }

    public virtual Medicament Medicament { get; set; }

}

}
